Require isort as a dependency
This dependency is called at the very end of generate_upstream.py via a subprocess. If the user doesn't have it installed, they'll get the following error when running it:

Traceback (most recent call last):
  File '/home/user/.local/bin/isort', line 5, in <module>
    from isort.main import main
ModuleNotFoundError: No module named 'isort'
Traceback (most recent call last):
  File 'PyQt6-stubs/generate_upstream.py', line 163, in <module>
    subprocess.check_call(['isort', '--profile', 'black', '-l 10000', 'PyQt6-stubs'])
  File '/usr/lib/python3.9/subprocess.py', line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['isort', '--profile', 'black', '-l 10000', 'PyQt6-stubs']' returned non-zero exit status 1.